name: test
on:
  - push
  - pull_request
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - run: go version
      - run: go test -v ./...
  make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cedrickring/golang-action@1.7.0
        with:
          args: make test
