on: push
name: Verify tests
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      uses: cedrickring/golang-action@1.6.0
      with:
        args: make test